const mongoose = require("mongoose");
const database = require("../../config/database");
const User = require("../models/User");

const users = [
  {
    user_id: "ef818302-a691-4a9a-bd39-ea4d1140a74a",
    email: "catpower@gmail.com",
    hashed_password: "$2b$10$LLcDkt8qMknE2OIJEXF0F.rPQMhb7f..ie9xw/417SME86tG7uWGy",
    first_name: "Cat Power",
    dob_day: "1",
    dob_month: "1",
    dob_year: "2010",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "Soy un gato juguetón, me encanta jugar al gato y al ratón",
    matches: [],
    banned: [],
  },
  {
    user_id: "8c2e9dd3-471a-4bbd-add0-47115a5acbc0",
    email: "garfield@gmail.com",
    hashed_password: "$2b$10$2j5sQcu1IzbKYQKpVqGtE.vFXZ9FzvZ5TUIFlMBeZQeeuoE9QsDVO",
    first_name: "Garfield",
    dob_day: "2",
    dob_month: "2",
    dob_year: "2011",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "Soy el gato más famoso de los 90s, exacto soy un pureta",
    matches: [],
    banned: [],
  },
  {
    user_id: "6c8f0849-18c7-40e8-98f0-cd2040c840b3",
    email: "moongose@gmail.com",
    hashed_password: "$2b$10$BmH.n4tDogoU7BVWhy.3JO2dXlRQYweSVRu/izVJW.pJVXEoWrOkm",
    first_name: "Moongose",
    dob_day: "3",
    dob_month: "3",
    dob_year: "2013",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "No sé si te vas a desesperar más conmigo o con mi colega MongoDB. Los dos somos maravillosos",
    matches: [],
    banned: [],
  },
  {
    user_id: "da8a5160-6664-44b1-a047-9d1bcd155375",
    email: "michi@gmail.com",
    hashed_password: "$2b$10$iSSTEW1.B6LelTk.a9rXJeY.k2Lb/NURts2ovcgY.pgAmJHzPsbve",
    first_name: "Michi",
    dob_day: "4",
    dob_month: "4",
    dob_year: "2014",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "En realidad no sé que hago por aquí con este calor, debería estar en las playas de Cádiz",
    matches: [],
    banned: [],
  },
  {
    user_id: "f625b4d8-0814-47b2-aa9b-66f3cecb0087",
    email: "calamardo@gmail.com",
    hashed_password: "$2b$10$3VXkonL8ZS0ZJ8cSuf3lneV7NVkjsTgteAT4492wEAcDl3evKpJQ2",
    first_name: "Calamardo",
    dob_day: "5",
    dob_month: "5",
    dob_year: "2015",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "Yo soy bastante más cachondo que el amigo de Bob Esponja",
    matches: [],
    banned: [],
  },
  {
    user_id: "98a74188-83b8-4d08-8051-d0e532344549",
    email: "adelito@gmail.com",
    hashed_password: "$2b$10$a9oTpdnOib0ciVbt6FQVjuf9p68SmXyYk.VGWE1IJUWh3eUNDkKhO",
    first_name: "Adelito",
    dob_day: "6",
    dob_month: "6",
    dob_year: "2016",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "Soy Adelito y me encantan las siestas los domingos por la tarde después de la paella",
    matches: [],
    banned: [],
  },
  {
    user_id: "580c069f-a16f-455c-8ab5-2d96c91082ad",
    email: "morrongo@gmail.com",
    hashed_password: "$2b$10$yX05r2IPn0S2rr3XbCMhJOxHAqGw3VnspCY8CDDvrhfLWrpsbPHkC",
    first_name: "Morrongo",
    dob_day: "7",
    dob_month: "7",
    dob_year: "2017",
    gender_identity: "male",
    gender_interest: "female",
    imageURL: "",
    about: "No me llaman morrongo por casualidad, soy más pesado que una tarde de verano",
    matches: [],
    banned: [],
  },
  {
    user_id: "19e657b5-f0eb-4c38-91ef-b253a8c0026a",
    email: "niebla@gmail.com",
    hashed_password: "$2b$10$ZJxFqXaGJMdBVjtxUBVN2.bLzjv2vxim9bdiulb0Qi5XvWMOMhtv.",
    first_name: "Niebla",
    dob_day: "1",
    dob_month: "1",
    dob_year: "2011",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "",
    matches: [],
    banned: [],
  },
  {
    user_id: "e644d0fc-7eaa-4bd9-9c77-98fce38435ce",
    email: "bandolera@gmail.com",
    hashed_password: "$2b$10$Oeq40KWHEWr/b0vo/EqDf.jSwWAr57S4aLUhtKqytRyBWhTMF8Iw6",
    first_name: "Bandolera",
    dob_day: "2",
    dob_month: "2",
    dob_year: "2012",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "Soy una gata silvestre y divertida",
    matches: [],
    banned: [],
  },
  {
    user_id: "6a3c161f-905a-4e7f-818f-e7d9293d178a",
    email: "wendy@gmail.com",
    hashed_password: "$2b$10$yi9QOAm4DfPQ883qgmu1we5AE3B90TGPyWm3ee6npJ7ngaeTvp972",
    first_name: "Wendy",
    dob_day: "3",
    dob_month: "3",
    dob_year: "2013",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "",
    matches: [],
    banned: [],
  },
  {
    user_id: "79565196-7036-477d-8b17-6ffa28483eeb",
    email: "salsa@gmail.com",
    hashed_password: "$2b$10$8UDvfXK2CjXvMDtpyZ5RwuEYpl.RzJiv3fhy0Yhshb93VVUvfwHb2",
    first_name: "Salsa",
    dob_day: "4",
    dob_month: "4",
    dob_year: "2014",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "",
    matches: [],
    banned: [],
  },
  {
    user_id: "4c553bda-8708-457c-862d-84d69886de75",
    email: "rafela@gmail.com",
    hashed_password: "$2b$10$Dan9Xo5NjsBCh7uKnTjYK.gu0aEG8k/GikzZzl6AybkqMUQvLAwO6",
    first_name: "Rafaela",
    dob_day: "5",
    dob_month: "5",
    dob_year: "2015",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "",
    matches: [],
    banned: [],
  },
  {
    user_id: "c2298350-bd0b-4dba-b084-682166311cd8",
    email: "tarantina@gmail.com",
    hashed_password: "$2b$10$DRglG0NMuF5mNYAOXDnPZ.0B0Xh1X.mvUSBsmAO8stIOr6wANTNA.",
    first_name: "Tarantina",
    dob_day: "6",
    dob_month: "6",
    dob_year: "2016",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "Me encanta el cine con diálogos increíbles, gangsters y mujeres explosivas",
    matches: [],
    banned: [],
  },
  {
    user_id: "281d8900-9cb6-4ba3-a513-cbac8598fbc6",
    email: "atletica@gmail.com",
    hashed_password: "$2b$10$g.rjcdLgVbVHNGcs7VIUpOGzQAm4AoiXT7T/RHAhz5couFeeHYOD6",
    first_name: "Atlética de Madrid",
    dob_day: "7",
    dob_month: "7",
    dob_year: "2017",
    gender_identity: "female",
    gender_interest: "male",
    imageURL: "",
    about: "Vaya rollo que el Real Madrid gane otra Champions más, pesados",
    matches: [],
    banned: [],
  },

  

];

const usersDocuments = users.map((user) => new User(user));

// Conectaremos con DB y desconectaremos tras insertar los documentos
database.connectDB()
// Ver si hay usuarios y eliminarlos
    .then(async () => {
        const allUsers = await User.find();
        if (allUsers.length > 0) {
          await User.collection.drop();
        }
    })
    .catch((err) => console.error(`Error eliminado información de la DB: ${err}`))

  // Añadir documentos de bicicletas a la base de datos
    .then(async () => {
        await User.insertMany(usersDocuments);
    })
    .catch((err) => console.error(`Error creando documentos en DB: ${err}`))

  // Cerrar la conexión
    .finally(() => mongoose.disconnect());